name: Nuget Exporter
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
jobs:
  nugetpush:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./ 
    steps:
      - uses: actions/checkout@main
      - name: debug
        run: ls
      - name: restore
        run: dotnet restore
      - name: build nuget
        run: dotnet pack -c Release
      - name: push nuget
        run: dotnet nuget push ./Kettle/bin/Release/Kettle.${{ github.event.inputs.tag }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
